import type { Product } from "./types"

export const products: Product[] = [
  {
    id: 1,
    slug: "airpods-pro",
    name: "AirPods Pro",
    description: "Active noise cancellation with transparency mode and spatial audio",
    company: "Apple",
    price: 249,
    imageSrc: "/images/product/airpods.avif",
    imageAlt: "Apple AirPods Pro wireless earbuds",
  },
  {
    id: 2,
    slug: "casio-aq230a-7avt",
    name: "Casio AQ230A-7AVT",
    description: "Digital-analog display watch with stopwatch and alarm functions",
    company: "Casio",
    price: 45,
    imageSrc: "/images/product/casio-AQ230A-7AVT.avif",
    imageAlt: "Casio digital-analog watch with silver case",
  },
  {
    id: 3,
    slug: "momentt-wall-clock",
    name: "Momentt Wall Clock",
    description: "Minimalist wall clock with silent movement and modern design",
    company: "Momentt",
    price: 89,
    imageSrc: "/images/product/momentt-wall-clock.avif",
    imageAlt: "Minimalist wall clock on a wall",
  },
  {
    id: 4,
    slug: "nothing-ear-2",
    name: "Nothing Ear (2)",
    description: "Wireless earbuds with active noise cancellation and transparent design",
    company: "Nothing",
    price: 149,
    imageSrc: "/images/product/nothing-earbuds.avif",
    imageAlt: "Nothing wireless earbuds with transparent design",
  },
  {
    id: 5,
    slug: "nothing-phone-3",
    name: "Nothing Phone (3)",
    description: "Smartphone with transparent back panel and Glyph interface",
    company: "Nothing",
    price: 699,
    imageSrc: "/images/product/nothing-phone-3.avif",
    imageAlt: "Nothing Phone 3 with transparent design",
  },
  {
    id: 6,
    slug: "sigma-bf-lens",
    name: "Sigma BF Lens",
    description: "Professional camera lens with wide aperture and optical stabilization",
    company: "Sigma",
    price: 899,
    imageSrc: "/images/product/sigma-BF.avif",
    imageAlt: "Sigma camera lens with black finish",
  },
  {
    id: 7,
    slug: "premium-t-shirt",
    name: "Premium T-Shirt",
    description: "Classic fit cotton t-shirt with minimal branding",
    company: "Basic Goods",
    price: 35,
    imageSrc: "/images/product/t-shirt.avif",
    imageAlt: "Plain t-shirt on white background",
  },
]
