import type { Product } from "./types"

export const products: Product[] = [
  {
    id: 1,
    slug: "airpods-pro",
    name: "AirPods Pro",
    description: "Active noise cancellation with transparency mode and spatial audio",
    company: "Apple",
    price: 249,
    imageSrc: "/images/product/airpods.avif",
    imageAlt: "Apple AirPods Pro wireless earbuds",
  },
  {
    id: 2,
    slug: "casio-aq230a-7avt",
    name: "Casio AQ230A-7AVT",
    description: "Digital-analog display watch with stopwatch and alarm functions",
    company: "Casio",
    price: 45,
    imageSrc: "/images/product/casio-AQ230A-7AVT.avif",
    imageAlt: "Casio digital-analog watch with silver case",
  },
  {
    id: 3,
    slug: "momentt-wall-clock",
    name: "Momentt Wall Clock",
    description: "Minimalist wall clock with silent movement and modern design",
    company: "Momentt",
    price: 89,
    imageSrc: "/images/product/momentt-wall-clock.avif",
    imageAlt: "Minimalist wall clock on a wall",
  },
  {
    id: 4,
    slug: "nothing-ear-2",
    name: "Nothing Ear (2)",
    description: "Wireless earbuds with active noise cancellation and transparent design",
    company: "Nothing",
    price: 149,
    imageSrc: "/images/product/nothing-earbuds.avif",
    imageAlt: "Nothing wireless earbuds with transparent design",
  },
  {
    id: 5,
    slug: "nothing-phone-3",
    name: "Nothing Phone (3)",
    description: "Smartphone with transparent back panel and Glyph interface",
    company: "Nothing",
    price: 699,
    imageSrc: "/images/product/nothing-phone-3.avif",
    imageAlt: "Nothing Phone 3 with transparent design",
  },
  {
    id: 6,
    slug: "sigma-bf-lens",
    name: "Sigma BF Lens",
    description: "Professional camera lens with wide aperture and optical stabilization",
    company: "Sigma",
    price: 899,
    imageSrc: "/images/product/sigma-BF.avif",
    imageAlt: "Sigma camera lens with black finish",
  },
  {
    id: 7,
    slug: "premium-t-shirt",
    name: "Premium T-Shirt",
    description: "Classic fit cotton t-shirt with minimal branding",
    company: "Basic Goods",
    price: 35,
    imageSrc: "/images/product/t-shirt.avif",
    imageAlt: "Plain t-shirt on white background",
  },
  {
    id: 8,
    slug: "altra-timp-5-boa",
    name: "Altra Timp 5 BOA",
    description: "Trail running shoe with BOA Fit System and Vibram Megagrip outsole for enhanced traction",
    company: "Altra",
    price: 175,
    imageSrc: "/images/product/altra-timp5-boa.avif",
    imageAlt: "Altra Timp 5 BOA trail running shoe",
  },
  {
    id: 9,
    slug: "apple-watch-series-11",
    name: "Apple Watch Series 11",
    description: "Smartwatch with S10 SiP chip, health monitoring, and up to 24 hours of battery life",
    company: "Apple",
    price: 329,
    imageSrc: "/images/product/apple-watch-11.avif",
    imageAlt: "Apple Watch Series 11 smartwatch",
  },
  {
    id: 10,
    slug: "penac-ele-001",
    name: "PENAC ELE-001",
    description: "3-in-1 multifunction pen with 360° twist mechanism, ballpoint pens, and mechanical pencil",
    company: "PENAC",
    price: 12,
    imageSrc: "/images/product/argument-a-001-pen.avif",
    imageAlt: "PENAC ELE-001 multifunction pen",
  },
  {
    id: 11,
    slug: "iphone-17-pro",
    name: "iPhone 17 Pro",
    description: "Flagship smartphone with A19 Pro chip, Pro Fusion camera system, and Ceramic Shield 2 display",
    company: "Apple",
    price: 999,
    imageSrc: "/images/product/iphone 17 pro.avif",
    imageAlt: "iPhone 17 Pro smartphone",
  },
]
